name: 'E2P Action Create Release'
description:
  'GitHub Action that generates version files, CHANGELOG.md and GitHub releases
  based on the Git history and commit messages.'
author: 'matchgroup-e2p'

inputs:
  token:
    description: 'The GitHub token'
    default: ${{ github.token }}
    required: true
  version:
    description: 'The version to release'
    required: true

runs:
  using: node20
  main: dist/index.js
