name: 'E2P Action Create Release'
description:
  'GitHub Action that generates version files, CHANGELOG.md and GitHub releases
  based on the Git history and commit messages.'
author: 'matchgroup-e2p'

inputs:
  token:
    description: 'The GitHub token'
    default: ${{ github.token }}
    required: true
  version:
    description: 'The version to release'
    required: true
  update_npm_package:
    description: 'Update the npm package version'
    default: 'false'
  npm_package_root_dir:
    description: 'Root directory of the npm package'
    default: ''
  update_csproj:
    description: 'Update the .csproj files'
    default: 'false'
  csproj_root_dir:
    description: 'Root directory of the .csproj files'
    default: ''
  update_version_sbt:
    description: 'Update the version.sbt file'
    default: 'false'
  version_sbt_root_dir:
    description: 'Root directory of the version.sbt file'
    default: ''
  update_helm_chart:
    description: 'Update the Chart.yaml file'
    default: 'false'
  helm_chart_root_dir:
    description: 'Root directory of the Chart.yaml file'
    default: ''

runs:
  using: node20
  main: dist/index.js
