name: 'E2P Create Release'
description: 'GitHub Action for creating releases'
author: 'matchgroup-e2p'

inputs:
  token:
    description: 'The GitHub token'
    default: ${{ github.token }}
    required: true
  version:
    description: 'The version to release'
    required: true

runs:
  using: node20
  main: dist/index.js
